### ISSUE TITLE
npm install not working on windows 7

### ISSUE THREAD

**Issue by suchetabanerjee** [SOHU-Co/kafka-node#202]
Hi I am new to kafka and trying to install the kafka-node but its been failing -
gyp ERR! stack Error: Python executable "python" is v3.4.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.

**Comment by estliberitas** [comment]
@suchetabanerjee it's a general issue and not related to `kafka-node`.

You see `kafka-node` uses `snappy` module. This module has native addon, so it has to be compiled during installation of `snappy`. And [node-gyp](https://github.com/TooTallNate/node-gyp) (Node.js native addon build tool) does not support python v3. In other words, to install modules with native addons you need python 2.7.x.

P.S.: look at Node.js [Installation - Known issues](https://github.com/joyent/node/wiki/Installation#known-issues) section, maybe it will help you to fix the issue.

**Comment by suchetabanerjee** [comment]
Thank you so much for your reply. I installed python 2.7 and tried the following command-npm install --python=Python27
and now i am stuck at visual c++ error!!!
This is very frustrating.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.
  [C:\GitHub\kafka-node-master\kafka-node-master\node_modules\snappy\build\binding.sln]
gyp ERR! build error

**Comment by estliberitas** [comment]
@suchetabanerjee what version of Visual Studio do you have?

**Comment by suchetabanerjee** [comment]
@estliberitas i am a little surprised to deal with such issues only when i am trying to install kafka-node.
I use node.js on a regular basis and have had to install a lot of packages but didn't have to deal with any such issues. Thanks for the help. Will try it with the latest VS .

**Comment by estliberitas** [comment]
@suchetabanerjee well, try `npm install hiredis`, for example. If you get same error again, than the problem is acutally with VS Compiler and native addons. So you will be sure problem is not with kafka-node )

**Comment by tobilg** [comment]
I'm getting a `C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform.Targets(23,7): error MSB8007: The Platform for project 'snappy.vcxproj' is invalid.  Platform='Win3
2'. You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Platform that doesn't exist for this project
. [D:\TM\WebStorm-Workspace\KafkaTest\node_modules\kafka-node\node_modules\snappy\build\deps\snappy\snappy.vcxproj]` error, having installed Visual Studio 2013 Express on Win7.

**Comment by haio** [comment]
what version of node.js are you using ? If it is 64 bit version node.js , you can try reinstall 32 bit version node.js

**Comment by tobilg** [comment]
I'm using the 64bit version currently, but I also tried what you suggested before. This resulted in a bunch of other errors. 

I guess it's not the fault of kafka-node, but node-gyp, which seems to be very error-prone on Windows. 

Baseline is I created a fork and removed the reference to snappy. Then I can use it without problems.

**Comment by AkramKamal** [comment]
I fixed the issue, I am using windows 7, Please follow the next steps to fix the issue:
1- Install python 2.7 from https://www.python.org/downloads/
2- open CMD and change the directory to root drive
3- Install node-gyp using command "npm install node-gyp -g --python=Python27"
4- Install the kafka module using "npm install kafka-node --python=Python27 --msvs_version=2012"

Note: if you have vs 2013 then replace the version

I hope it works for you guys!

**Comment by tobilg** [comment]
Thanks @AkramKamal I followed all of the steps, but still no luck. It seems like node-gyp is pulling the wrong version of MSBuild.exe, but I can't seem to fix this. 

Error message:

`C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\x64\Microsoft.Cpp.x64.Targets(507,5): error MSB8008: Specified platform toolset (v120) is not installed or invalid. Please make sure that a supported PlatformToolset value is selected.`

**Comment by AkramKamal** [comment]
@tobilg are you sure you set the right version  --msvs_version=2012
if you have vs 2013 then use  --msvs_version=2013

**Comment by tobilg** [comment]
I already did what you outlined. It just ignores the msvs_version parameter unfortunately regarding the msbuild.exe version. Setting the correct path variables also doesn't help.

**Comment by AkramKamal** [comment]
@tobilg If you have a team viewer then i can try fix the issue

**Comment by hyperlink** [comment]
closing since snappy is optional now.

**Comment by NhokCrazy199** [comment]
You must try "npm install --global --production windows-build-tools", so easy to fix it
